### ISSUE TITLE
Crash on every invokation

### ISSUE THREAD

**Issue by darnir** [vrothberg/vgrep#22]
After upgrading to the latest release, I see vgrep crashing on every invokation with the following trace:

```
Traceback (most recent call last):
  File "/usr/bin/vgrep", line 965, in <module>
    main()
  File "/usr/bin/vgrep", line 112, in main
    slocs = grep(grep_args, args.nogit, args.nogitsubmodules)
  File "/usr/bin/vgrep", line 786, in grep
    lines = execute(sub_grep_cmd, failOK=True).rsplit("\n")
  File "/usr/bin/vgrep", line 724, in execute
    stdout = subp.check_output(cmd, stderr=subp.STDOUT, shell=False, env=env)
  File "/usr/lib/python3.5/subprocess.py", line 626, in check_output
    **kwargs).stdout
  File "/usr/lib/python3.5/subprocess.py", line 693, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/lib/python3.5/subprocess.py", line 947, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.5/subprocess.py", line 1551, in _execute_child
    raise child_exception_type(errno_num, err_msg)
FileNotFoundError: [Errno 2] No such file or directory: 'cd'

```

**Comment by vrothberg** [comment]
Hi darnir,

thanks a lot for reporting the issue.  I could fix the issue with commit f4045fc324a682f17538b892691a4de508c74ed9 on my local machine with a test git and some submodules.

Does this work for you?

**Comment by darnir** [comment]
Thasnk @vrothberg. That commit indeed fixes the issue.
Could you please make a new bugfix release with this commit since this is a major breakage?

**Comment by vrothberg** [comment]
Hi darnir,

thank you reporting and testing.  Sure, I will prepare a new bugfix release.
