### ISSUE TITLE
vgrep with no options fails with a traceback

### ISSUE THREAD

**Issue by gregkh** [vrothberg/vgrep#3]
$ vgrep
Traceback (most recent call last):
  File "/home/gregkh/bin/vgrep", line 253, in <module>
    main()
  File "/home/gregkh/bin/vgrep", line 115, in main
    if not hits:
UnboundLocalError: local variable 'hits' referenced before assignment

**Comment by vrothberg** [comment]
Thanks a lot, I fixed it!
