### ISSUE TITLE
-A -B and -C options don't work

### ISSUE THREAD

**Issue by marcosnils** [vrothberg/vgrep#84]
```
marcos:wl/clusters (master) $ vgrep -A 1 test
panic: runtime error: index out of range [1] with length 1

goroutine 1 [running]:
main.(*vgrep).splitMatch(0xc0001841e0, 0xc0001c60a5, 0xa, 0x1, 0xc00018e460, 0xb, 0xc00018e46b, 0x3, 0xc00018e470, 0xe)
        /home/marcos/Projects/gopath/src/github.com/vrothberg/vgrep/vgrep.go:253 +0x471
main.(*vgrep).grep(0xc0001841e0, 0xc000188080, 0x3, 0x4)
        /home/marcos/Projects/gopath/src/github.com/vrothberg/vgrep/vgrep.go:233 +0x35f
main.main()
        /home/marcos/Projects/gopath/src/github.com/vrothberg/vgrep/vgrep.go:105 +0x46e
```

Getting a index ouf range when using any of those options.

**Comment by vrothberg** [comment]
Thanks for opening the issue!

I took a quick look and believe to have a way forward.

**Comment by vrothberg** [comment]
I opened https://github.com/vrothberg/vgrep/pull/88 to address the issue. Lines that don't match the expected format are now being ignored. Does that work for you?
